name: r-java-gee-environment
channels:
  - conda-forge
  - defaults
dependencies:
  # Java setup
  - openjdk=11
  - maven

  # R setup
  - r-base
  - r-essentials
  - r-tidyverse
  - r-ggplot2

  # Python setup
  - python>=3.8
  - earthengine-api  # Google Earth Engine API
  - requests
  - pandas
  - numpy

  # Jupyter support
  - notebook
  - jupyterlab
